// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqowmukmodurkpeonnbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxb3dtdWttb2R1cmtwZW9ubmJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MzgyMTEsImV4cCI6MjA2NTMxNDIxMX0.15vdi8IKOJpsJJLazk4KC4kZGPxo0YshxzeCHsmOhi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);